# Generated by Django 4.2.2 on 2023-06-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(blank=True, upload_to='static/portfolio/images')),
                ('anoRealizacao', models.IntegerField()),
                ('linkGitHub', models.CharField(blank=True, max_length=1000, null=True)),
                ('linkYt', models.CharField(blank=True, max_length=1000, null=True)),
                ('participantes', models.ManyToManyField(blank=True, to='portfolio.pessoa')),
                ('tecnologias', models.ManyToManyField(blank=True, to='portfolio.tecnologia')),
            ],
        ),
    ]
