# Generated by Django 4.2.2 on 2023-06-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_certificados'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnologiaUsadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('acronimo', models.CharField(blank=True, max_length=10)),
                ('anoCriacao', models.IntegerField()),
                ('criador', models.CharField(max_length=80)),
                ('logotipo', models.ImageField(upload_to='static/portfolio/images')),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
    ]
